# Predicting the Survivability of the Passenger on the Titanic

In [41]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8466764211454161927
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 1734816564
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 5698846438470417513
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
 xla_global_id: 416903419]

In [42]:
import sklearn 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [43]:
df_train = pd.read_csv("./titanic_train.csv")
df_test  = pd.read_csv("./titanic_test.csv")

In [44]:
df_train.drop(["PassengerId", "Ticket", "Cabin", "Embarked", "Name"], axis=1, inplace=True)
df_test.drop(["PassengerId", "Ticket", "Cabin", "Embarked", "Name"], axis=1, inplace=True)

In [46]:
df_train['male'] = (df_train['Sex'] == 'male').astype(int)
df_test['male'] = (df_test['Sex'] == 'male').astype(int)

In [47]:
df_train.drop('Sex', axis=1, inplace=True)
df_test.drop('Sex', axis=1, inplace=True)

In [48]:
features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'male']

In [49]:
df_train.dropna(how='any', axis=0, inplace=True)

In [50]:
df_train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  male
0         0       3  22.0      1      0   7.2500     1
1         1       1  38.0      1      0  71.2833     0
2         1       3  26.0      0      0   7.9250     0
3         1       1  35.0      1      0  53.1000     0
4         0       3  35.0      0      0   8.0500     1

In [51]:
X_train = df_train[features]
X_train

Pclass   Age  SibSp  Parch     Fare  male
0         3  22.0      1      0   7.2500     1
1         1  38.0      1      0  71.2833     0
2         3  26.0      0      0   7.9250     0
3         1  35.0      1      0  53.1000     0
4         3  35.0      0      0   8.0500     1
..      ...   ...    ...    ...      ...   ...
885       3  39.0      0      5  29.1250     0
886       2  27.0      0      0  13.0000     1
887       1  19.0      0      0  30.0000     0
889       1  26.0      0      0  30.0000     1
890       3  32.0      0      0   7.7500     1

[714 rows x 6 columns]

In [52]:
y_train = df_train['Survived']
y_train

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [53]:
df_test.dropna(how='any', axis=0, inplace=True)

In [54]:
X_test = df_test
X_test

Pclass   Age  SibSp  Parch      Fare  male
0         3  34.5      0      0    7.8292     1
1         3  47.0      1      0    7.0000     0
2         2  62.0      0      0    9.6875     1
3         3  27.0      0      0    8.6625     1
4         3  22.0      1      1   12.2875     0
..      ...   ...    ...    ...       ...   ...
409       3   3.0      1      1   13.7750     0
411       1  37.0      1      0   90.0000     0
412       3  28.0      0      0    7.7750     0
414       1  39.0      0      0  108.9000     0
415       3  38.5      0      0    7.2500     1

[331 rows x 6 columns]

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
logModel = LogisticRegression()

In [57]:
logModel.fit(X_train.values, y_train.values)

LogisticRegression()

In [58]:
logModel.predict(X_test.values)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,

In [59]:
logModel.score(X_train.values, y_train.values)

0.8025210084033614

In [60]:
a = logModel.predict([[1,26,0,0,15,False]])

In [61]:
print(a[0])

1


In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
ForestModel = RandomForestClassifier(n_estimators = 10000, max_depth=20)

In [64]:
%%time
ForestModel.fit(X_train.values, y_train.values)

CPU times: total: 2.53 s
Wall time: 11.6 s


RandomForestClassifier(max_depth=20, n_estimators=10000)

In [65]:
%%time
ForestModel.predict(X_test.values)

CPU times: total: 141 ms
Wall time: 870 ms


array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,

In [66]:
%%time
ForestModel.score(X_train.values, y_train.values)

CPU times: total: 297 ms
Wall time: 1.32 s


0.9859943977591037

In [71]:
ForestModel.predict([[3, 23, 4, 0, 23, True]])

array([0], dtype=int64)

In [72]:
X_test.head(1).values

array([[ 3.    , 34.5   ,  0.    ,  0.    ,  7.8292,  1.    ]])

In [73]:
ForestModel.predict([[3, 34.5, 0, 0, 7.8292, True]])

array([0], dtype=int64)

In [74]:
ForestModel.predict([[1,26,0,0,15,False]])

array([1], dtype=int64)

In [75]:
a = ForestModel.predict([[1,26,0,0,15,False]])

In [76]:
print(a)

[1]
